/**
 * Seed Data: Instituciones Masivas
 * 40 instituciones (10 por sistema educativo)
 * Para demostrar el sistema con volumen realista segun TPO
 */

const instituciones = [
  // ============================================
  // UK - Reino Unido (10 instituciones)
  // ============================================
  {
    codigo: 'UK-OXF-001',
    nombre: 'Oxford High School',
    nombreCorto: 'Oxford High',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Oxfordshire',
    ciudad: 'Oxford',
    direccion: { calle: '21 Banbury Road', codigoPostal: 'OX2 6PE' },
    telefono: '+44 1865 559888',
    email: 'info@oxfordhigh.gdst.net',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-CAM-002',
    nombre: 'Cambridge Academy',
    nombreCorto: 'Cambridge Acad',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Cambridgeshire',
    ciudad: 'Cambridge',
    direccion: { calle: '15 Hills Road', codigoPostal: 'CB2 1PH' },
    telefono: '+44 1223 712000',
    email: 'admissions@cambridgeacademy.edu',
    nivelesEducativos: ['GCSE', 'A-Level', 'AS-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-LON-003',
    nombre: 'London Grammar School',
    nombreCorto: 'London Grammar',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Greater London',
    ciudad: 'London',
    direccion: { calle: '100 Kensington High Street', codigoPostal: 'W8 4SG' },
    telefono: '+44 20 7938 1234',
    email: 'info@londongrammar.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-MAN-004',
    nombre: 'Manchester College',
    nombreCorto: 'Manchester Col',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Greater Manchester',
    ciudad: 'Manchester',
    direccion: { calle: '45 Oxford Road', codigoPostal: 'M1 6FQ' },
    telefono: '+44 161 234 5678',
    email: 'info@manchestercollege.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-BIR-005',
    nombre: 'Birmingham Institute',
    nombreCorto: 'Birmingham Inst',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'West Midlands',
    ciudad: 'Birmingham',
    direccion: { calle: '78 New Street', codigoPostal: 'B2 4BA' },
    telefono: '+44 121 456 7890',
    email: 'info@birminghaminstitute.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-LEE-006',
    nombre: 'Leeds Secondary School',
    nombreCorto: 'Leeds Secondary',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'West Yorkshire',
    ciudad: 'Leeds',
    direccion: { calle: '23 Park Row', codigoPostal: 'LS1 5HD' },
    telefono: '+44 113 234 5678',
    email: 'info@leedssecondary.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-BRI-007',
    nombre: 'Bristol Academy',
    nombreCorto: 'Bristol Acad',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Bristol',
    ciudad: 'Bristol',
    direccion: { calle: '56 College Green', codigoPostal: 'BS1 5TB' },
    telefono: '+44 117 925 4321',
    email: 'info@bristolacademy.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-LIV-008',
    nombre: 'Liverpool School',
    nombreCorto: 'Liverpool Sch',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Merseyside',
    ciudad: 'Liverpool',
    direccion: { calle: '89 Hope Street', codigoPostal: 'L1 9BW' },
    telefono: '+44 151 708 9876',
    email: 'info@liverpoolschool.edu',
    nivelesEducativos: ['GCSE', 'A-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-EDI-009',
    nombre: 'Edinburgh High School',
    nombreCorto: 'Edinburgh High',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Scotland',
    ciudad: 'Edinburgh',
    direccion: { calle: '12 Royal Mile', codigoPostal: 'EH1 1QB' },
    telefono: '+44 131 220 3344',
    email: 'info@edinburghhigh.edu',
    nivelesEducativos: ['GCSE', 'A-Level', 'AS-Level'],
    estado: 'activa'
  },
  {
    codigo: 'UK-GLA-010',
    nombre: 'Glasgow Institute',
    nombreCorto: 'Glasgow Inst',
    tipo: 'secundaria',
    sistemaEducativo: 'UK',
    pais: 'Reino Unido',
    region: 'Scotland',
    ciudad: 'Glasgow',
    direccion: { calle: '34 George Square', codigoPostal: 'G2 1EQ' },
    telefono: '+44 141 552 4400',
    email: 'info@glasgowinstitute.edu',
    nivelesEducativos: ['GCSE', 'A-Level', 'AS-Level'],
    estado: 'activa'
  },

  // ============================================
  // US - Estados Unidos (10 instituciones)
  // ============================================
  {
    codigo: 'US-LHS-001',
    nombre: 'Lincoln High School',
    nombreCorto: 'Lincoln HS',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'California',
    ciudad: 'San Francisco',
    direccion: { calle: '2162 24th Avenue', codigoPostal: '94116' },
    telefono: '+1 415-759-2700',
    email: 'lincolnhs@sfusd.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-WAS-002',
    nombre: 'Washington Academy',
    nombreCorto: 'Washington Acad',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'District of Columbia',
    ciudad: 'Washington DC',
    direccion: { calle: '1776 Constitution Ave', codigoPostal: '20004' },
    telefono: '+1 202-555-0100',
    email: 'info@washingtonacademy.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-JEF-003',
    nombre: 'Jefferson High School',
    nombreCorto: 'Jefferson HS',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Virginia',
    ciudad: 'Charlottesville',
    direccion: { calle: '456 Main Street', codigoPostal: '22901' },
    telefono: '+1 434-555-0200',
    email: 'info@jeffersonhs.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-ROO-004',
    nombre: 'Roosevelt Secondary',
    nombreCorto: 'Roosevelt Sec',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'New York',
    ciudad: 'New York City',
    direccion: { calle: '789 Fifth Avenue', codigoPostal: '10022' },
    telefono: '+1 212-555-0300',
    email: 'info@rooseveltsecondary.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-KEN-005',
    nombre: 'Kennedy Institute',
    nombreCorto: 'Kennedy Inst',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Massachusetts',
    ciudad: 'Boston',
    direccion: { calle: '100 Harvard Way', codigoPostal: '02138' },
    telefono: '+1 617-555-0400',
    email: 'info@kennedyinstitute.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-MAD-006',
    nombre: 'Madison School',
    nombreCorto: 'Madison Sch',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Wisconsin',
    ciudad: 'Madison',
    direccion: { calle: '200 State Street', codigoPostal: '53703' },
    telefono: '+1 608-555-0500',
    email: 'info@madisonschool.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-HAM-007',
    nombre: 'Hamilton Academy',
    nombreCorto: 'Hamilton Acad',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Texas',
    ciudad: 'Houston',
    direccion: { calle: '321 Space Center Blvd', codigoPostal: '77058' },
    telefono: '+1 281-555-0600',
    email: 'info@hamiltonacademy.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-FRA-008',
    nombre: 'Franklin High School',
    nombreCorto: 'Franklin HS',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Pennsylvania',
    ciudad: 'Philadelphia',
    direccion: { calle: '500 Independence Mall', codigoPostal: '19106' },
    telefono: '+1 215-555-0700',
    email: 'info@franklinhs.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-ADA-009',
    nombre: 'Adams College Prep',
    nombreCorto: 'Adams Prep',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Illinois',
    ciudad: 'Chicago',
    direccion: { calle: '100 Michigan Avenue', codigoPostal: '60601' },
    telefono: '+1 312-555-0800',
    email: 'info@adamsprep.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },
  {
    codigo: 'US-JAC-010',
    nombre: 'Jackson Institute',
    nombreCorto: 'Jackson Inst',
    tipo: 'secundaria',
    sistemaEducativo: 'US',
    pais: 'Estados Unidos',
    region: 'Florida',
    ciudad: 'Miami',
    direccion: { calle: '800 Ocean Drive', codigoPostal: '33139' },
    telefono: '+1 305-555-0900',
    email: 'info@jacksoninstitute.edu',
    nivelesEducativos: ['High School'],
    estado: 'activa'
  },

  // ============================================
  // DE - Alemania (10 instituciones)
  // ============================================
  {
    codigo: 'DE-GYM-001',
    nombre: 'Gymnasium Berlin-Mitte',
    nombreCorto: 'Gym Berlin',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Berlin',
    ciudad: 'Berlin',
    direccion: { calle: 'Weinmeisterstrasse 15', codigoPostal: '10178' },
    telefono: '+49 30 24725500',
    email: 'info@gymnasium-berlin-mitte.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-RSM-002',
    nombre: 'Realschule Munchen',
    nombreCorto: 'RS Munchen',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Bayern',
    ciudad: 'Munchen',
    direccion: { calle: 'Landsberger Strasse 428', codigoPostal: '81241' },
    telefono: '+49 89 82070',
    email: 'sekretariat@rs-muenchen.de',
    nivelesEducativos: ['Realschule'],
    estado: 'activa'
  },
  {
    codigo: 'DE-GYH-003',
    nombre: 'Gymnasium Hamburg',
    nombreCorto: 'Gym Hamburg',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Hamburg',
    ciudad: 'Hamburg',
    direccion: { calle: 'Rothenbaumchaussee 78', codigoPostal: '20148' },
    telefono: '+49 40 428839200',
    email: 'info@gymnasium-hamburg.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-SCF-004',
    nombre: 'Schule Frankfurt',
    nombreCorto: 'Schule Frankfurt',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Hessen',
    ciudad: 'Frankfurt am Main',
    direccion: { calle: 'Senckenberganlage 15', codigoPostal: '60325' },
    telefono: '+49 69 798750',
    email: 'info@schule-frankfurt.de',
    nivelesEducativos: ['Gymnasium', 'Realschule'],
    estado: 'activa'
  },
  {
    codigo: 'DE-INK-005',
    nombre: 'Institut Koln',
    nombreCorto: 'Inst Koln',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Nordrhein-Westfalen',
    ciudad: 'Koln',
    direccion: { calle: 'Domplatz 12', codigoPostal: '50667' },
    telefono: '+49 221 9281234',
    email: 'info@institut-koln.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-GYS-006',
    nombre: 'Gymnasium Stuttgart',
    nombreCorto: 'Gym Stuttgart',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Baden-Wurttemberg',
    ciudad: 'Stuttgart',
    direccion: { calle: 'Konigstrasse 45', codigoPostal: '70173' },
    telefono: '+49 711 2162000',
    email: 'info@gymnasium-stuttgart.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-SCD-007',
    nombre: 'Schule Dusseldorf',
    nombreCorto: 'Schule Dusseldorf',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Nordrhein-Westfalen',
    ciudad: 'Dusseldorf',
    direccion: { calle: 'Konigsallee 100', codigoPostal: '40212' },
    telefono: '+49 211 8996000',
    email: 'info@schule-duesseldorf.de',
    nivelesEducativos: ['Gymnasium', 'Realschule'],
    estado: 'activa'
  },
  {
    codigo: 'DE-IND-008',
    nombre: 'Institut Dresden',
    nombreCorto: 'Inst Dresden',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Sachsen',
    ciudad: 'Dresden',
    direccion: { calle: 'Altmarkt 25', codigoPostal: '01067' },
    telefono: '+49 351 4882000',
    email: 'info@institut-dresden.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-GYL-009',
    nombre: 'Gymnasium Leipzig',
    nombreCorto: 'Gym Leipzig',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Sachsen',
    ciudad: 'Leipzig',
    direccion: { calle: 'Augustusplatz 10', codigoPostal: '04109' },
    telefono: '+49 341 9737000',
    email: 'info@gymnasium-leipzig.de',
    nivelesEducativos: ['Gymnasium', 'Abitur'],
    estado: 'activa'
  },
  {
    codigo: 'DE-SCH-010',
    nombre: 'Schule Hannover',
    nombreCorto: 'Schule Hannover',
    tipo: 'secundaria',
    sistemaEducativo: 'DE',
    pais: 'Alemania',
    region: 'Niedersachsen',
    ciudad: 'Hannover',
    direccion: { calle: 'Ernst-August-Platz 8', codigoPostal: '30159' },
    telefono: '+49 511 1680000',
    email: 'info@schule-hannover.de',
    nivelesEducativos: ['Gymnasium', 'Realschule'],
    estado: 'activa'
  },

  // ============================================
  // AR - Argentina (10 instituciones)
  // ============================================
  {
    codigo: 'AR-CNB-001',
    nombre: 'Colegio Nacional de Buenos Aires',
    nombreCorto: 'CNBA',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Buenos Aires',
    ciudad: 'Ciudad Autonoma de Buenos Aires',
    direccion: { calle: 'Bolivar 263', codigoPostal: 'C1066AAE' },
    telefono: '+54 11 4331-0133',
    email: 'info@cnba.uba.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-ISJ-002',
    nombre: 'Instituto San Jose',
    nombreCorto: 'San Jose',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Buenos Aires',
    ciudad: 'La Plata',
    direccion: { calle: 'Calle 48 N 550', codigoPostal: 'B1900' },
    telefono: '+54 221 421-5800',
    email: 'info@institutosanjose.edu.ar',
    nivelesEducativos: ['Primario', 'Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-ENL-003',
    nombre: 'Escuela Normal La Plata',
    nombreCorto: 'Normal La Plata',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Buenos Aires',
    ciudad: 'La Plata',
    direccion: { calle: 'Calle 13 N 234', codigoPostal: 'B1900' },
    telefono: '+54 221 427-1234',
    email: 'info@normallaplata.edu.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-CDS-004',
    nombre: 'Colegio del Salvador',
    nombreCorto: 'Del Salvador',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Buenos Aires',
    ciudad: 'Ciudad Autonoma de Buenos Aires',
    direccion: { calle: 'Callao 542', codigoPostal: 'C1022AAL' },
    telefono: '+54 11 4373-5144',
    email: 'info@colegiodelsalvador.edu.ar',
    nivelesEducativos: ['Primario', 'Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-IBE-005',
    nombre: 'Instituto Belgrano',
    nombreCorto: 'Belgrano',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Buenos Aires',
    ciudad: 'Ciudad Autonoma de Buenos Aires',
    direccion: { calle: 'Juramento 2800', codigoPostal: 'C1428' },
    telefono: '+54 11 4788-5600',
    email: 'info@institutobelgrano.edu.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-ETC-006',
    nombre: 'Escuela Tecnica Cordoba',
    nombreCorto: 'Tecnica Cordoba',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Cordoba',
    ciudad: 'Cordoba',
    direccion: { calle: 'Av. Velez Sarsfield 200', codigoPostal: 'X5000' },
    telefono: '+54 351 433-2000',
    email: 'info@tecnicacordoba.edu.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-CSF-007',
    nombre: 'Colegio Santa Fe',
    nombreCorto: 'Santa Fe',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Santa Fe',
    ciudad: 'Santa Fe',
    direccion: { calle: 'San Martin 1500', codigoPostal: 'S3000' },
    telefono: '+54 342 456-7890',
    email: 'info@colegiosantafe.edu.ar',
    nivelesEducativos: ['Primario', 'Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-IME-008',
    nombre: 'Instituto Mendoza',
    nombreCorto: 'Mendoza',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Mendoza',
    ciudad: 'Mendoza',
    direccion: { calle: 'San Martin 500', codigoPostal: 'M5500' },
    telefono: '+54 261 429-3000',
    email: 'info@institutomendoza.edu.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-ERO-009',
    nombre: 'Escuela Rosario',
    nombreCorto: 'Rosario',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Santa Fe',
    ciudad: 'Rosario',
    direccion: { calle: 'Cordoba 1200', codigoPostal: 'S2000' },
    telefono: '+54 341 425-6789',
    email: 'info@escuelarosario.edu.ar',
    nivelesEducativos: ['Primario', 'Secundario'],
    estado: 'activa'
  },
  {
    codigo: 'AR-CTU-010',
    nombre: 'Colegio Tucuman',
    nombreCorto: 'Tucuman',
    tipo: 'secundaria',
    sistemaEducativo: 'AR',
    pais: 'Argentina',
    region: 'Tucuman',
    ciudad: 'San Miguel de Tucuman',
    direccion: { calle: '25 de Mayo 300', codigoPostal: 'T4000' },
    telefono: '+54 381 422-1234',
    email: 'info@colegiotucuman.edu.ar',
    nivelesEducativos: ['Secundario'],
    estado: 'activa'
  }
];

module.exports = instituciones;
